routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () { return redirect()->route('dashboard'); });
Route::group(['middleware' => ['web', 'auth']], function () {
    
    Route::get('dashboard', 'DashboardController')->name('dashboard');
    
    Route::post('ajax_select/{type}', 'AjaxSelectController')->name('ajaxSelect');

	
    Route::get('client/all', 'ClientController@all')->name('client.all');
    Route::post('client/import', 'ClientController@import')->name('client.import');
    Route::resource('client', 'ClientController')
        ->parameters(['client' => 'client'])->except('create', 'edit', 'show');
        
    Route::post('message/all', 'MessageController@all')->name('message.all');
    Route::post('message/setAll/{id}', 'MessageController@setAll')->name('message.setAll');
    Route::resource('message', 'MessageController')
        ->parameters(['message' => 'message'])->except('create', 'edit', 'show');

    Route::get('send/all', 'SendController@all')->name('send.all');
    Route::post('send/send', 'SendController@send')->name('send.send');
    Route::resource('send', 'SendController')
        ->parameters(['send' => 'send'])->except('create', 'edit', 'show');

    // Route::post('topUp/check_daterange', 'TopUpController@checkDaterange')->name('topUp.check_daterange');
    // Route::post('topUp/all', 'TopUpController@all')->name('topUp.all');
    // Route::post('topUp/export_excel', 'TopUpController@exportExcel')->name('topUp.export_excel');
    // Route::post('topUp/transaction_detail', 'TopUpController@transactionDetail')->name('topUp.transaction_detail');
    // Route::resource('topUp', 'TopUpController')
    //     ->parameters(['topUp' => 'topUp'])->except('create', 'edit', 'show');
        
    // Route::post('AccountTransactionSummaries/check_daterange', 'AccountTransactionSummariesController@checkDaterange')->name('AccountTransactionSummaries.check_daterange');
    // Route::get('AccountTransactionSummaries/all', 'AccountTransactionSummariesController@all')->name('AccountTransactionSummaries.all');
    // Route::resource('AccountTransactionSummaries', 'AccountTransactionSummariesController')
    //     ->parameters(['AccountTransactionSummaries' => 'AccountTransactionSummaries'])->except('create', 'edit', 'show');
    
    // Route::prefix('accountHistoryTransaction')->group(function () {
    //     Route::post('all', 'AccountHistoryTransactionController@all')->name('accountHistoryTransaction.all');
    //     Route::post('export_excel', 'AccountHistoryTransactionController@export_excel')->name('accountHistoryTransaction.export_excel');
    // });
    // Route::resource('accountHistoryTransaction', 'AccountHistoryTransactionController')
    //     ->parameters(['accountHistoryTransaction' => 'accountHistoryTransaction'])->except('create', 'edit', 'show');


});

Auth::routes([
    'register'  => true,
    'verify'    => false,
    'reset'     => false,
    'confirm'   => false,
]);

app/Models/Send.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Traits\DataCreatorUpdator;

class Send extends Model
{
    use DataCreatorUpdator;

    protected $table = 'send';
    protected $casts = [ 'created_at' => 'datetime:Y-m-d H:i:s', 'updated_at' => 'datetime:Y-m-d H:i:s' ];
    protected $guarded = ['id'];
}

app/Http/Controllers/SendController.php
<?php

namespace App\Http\Controllers;

use App\Models\Send;
use Illuminate\Http\Request;
use App\Http\Requests\SendRequest;
use DB;
use Illuminate\Support\Facades\Http;

class SendController extends Controller
{
    public function index()
    {
        $dataMessage = DB::table('message')->get();
        $dataType = DB::table('broadcast_type')->get();
        $dataClient = DB::table('client')->get();
       
        return view('contents.send.index', compact('dataMessage','dataClient','dataType'));
    }
    public function all(Request $request)
    {
        abort_if(!$request->header('X-XSRF-TOKEN'), 404);
        return Send::join('message','message.id','=','send.message_id')
        ->join('client','client.id','=','send.client_id')
        ->where('send.status','0')
        ->get([
            'send.*',
            'client.client_phone',
            'client.client_name',
            'message.title',
            'message.message',
        ]);
        
    }
    public function store(SendRequest $request)
    {
        // dd($request->all());
        if(!$request->client_id){
            //$client_phone=DB::table('client')->where('id',1)->select('id')->get();
            $payload=[
                'id'=>$request->id,
                'message_id'=>$request->message_id,
                'index'=>'0'.$request->message_id,
                'client_id'=>1,
                'broadcast_type_id'=>$request->broadcast_type,
                'status'=>0,
            ];
            // dd($payload);
        }else{
            // $client=DB::table('client')
            // ->where('id',$request->client_id)
            // ->select('client_phone')->first();
            $payload=[
                'id'=>$request->id,
                'message_id'=>$request->message_id,
                'client_id'=>$request->client_id,
                'index'=>$request->client_id.$request->message_id,
                'broadcast_type_id'=>$request->broadcast_type,
                'status'=>0,
            ];
            // dd($payload);
        }
            // dump($payload);
            $save=Send::create($payload);
        return $save;
    }
    public function update(SendRequest $request, Send $send)
    {
        $send->update($request->validated());
        return true;
    }
    public function destroy(Send $send)
    {
        $send->delete();
        return true;
    }
    public function send(Request $request)
    {  //dd($request->all());
        try{
        if($request->broadcast_type_id==1){
            $max=DB::table('client')->select(DB::raw('count(id)'))->first();
            $nomer=DB::table('client')->select('client_phone')->get();
            $text=DB::table('send')->join('message','message.id','=','send.message_id')
            // ->join('client','client.id','=','send.client_id')
            ->where('send.id',$request->id)
            ->select('message.message')->first();
            dd($nomer);
            for ($i=0; $i < $max->count ; $i++) { 
                // $payload=[
                //     'nomer'=>"89678971119",//substr($nomer[$i]->client_phone,1),
                //     'text'=>$text->message,
                // ];
                // $response=HTTP::post('http://localhost:10010/whatsapp/v1/send',$payload)->json();
        // return $response;
                     $res = HTTP::post('http://localhost:8000/send-message', [
                         'form_params' => [
                             'number'=>"6289678971119@c.us",//substr($nomer[$i]->client_phone,1),
                                 'message'=>$text->message,
                         ]
                     ]);
        

            }
        }else{       
            try{
            $text=DB::table('send')->join('message','message.id','=','send.message_id')
            ->join('client','client.id','=','send.client_id')
            ->where('send.id',$request->id)
            ->select('message.message','client.client_phone')->first();
            $rand=mt_rand(1, 3);
            $randnumb=strval($rand);
            $payload=[
                'no'=>substr($text->client_phone,1),
                'text'=>$text->message,
                'index'=>$randnumb,
            ];
            dump($payload);
            $response=HTTP::post('http://localhost:8000/whatsapp/v1/cek',$payload)->json();
            if($response['status']=="00"){
                DB::table("send")
                ->where('id',$request->id)
                ->update(['status'=>'1']);
            }
            // $nomer="62".substr($text->client_phone,1)."@c.us";
            // $res = HTTP::asForm()->post('http://localhost:8000/send-message', [
            //         'number'=>$nomer,//"6289678971119@c.us",//substr($nomer[$i]->client_phone,1),
            //         // 'nomer'=>"62"."89678971119"."@c.us",//substr($text->client_phone,1),   
            //         'message'=>$text->message,
                
            // ]);
            
            // dump($nomer);
            // if($res['status']=="true"){
            //         DB::table("send")
            //         ->where('id',$request->id)
            //         ->update(['status'=>'1']);
            //     }
            // dump($res['status']);
            return $response;
        } catch (\Exception $e) {
            return response()->json([
                'message' => 'Maaf terjadi kesalahan',
                'additional message' => $e->getMessage()
            ], 409);
        }
            // if($response->status=="success"){
            //     DB::table("send")->update('status','1')->where('id',$request->id);
            // }
        }
        
    } catch (\Exception $e) {
        // if($response->status!="00"){
        return response()->json([
            'message' => 'Maaf terjadi kesalahan',
            'additional message' => $e->getMessage()
        ], 409);
        // }
    }
    }
}

resources/views/contents/send/index.blade.php
@extends('layouts.template', [
    'pageTitle' => 'Send',
    'activeMenu' => 'send'
])

@section('breadcrumb')
<div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
	<div class="d-flex">
		<div class="breadcrumb">
			<a href="{{ route('dashboard') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Dashboard</a>
			<span class="breadcrumb-item">Corporate</span>
			<span class="breadcrumb-item active">Send</span>
		</div>
	</div>
</div>
@endsection

@section('content')
<!-- Basic datatable -->
<div class="card">
	<div class="card-header header-elements-inline">
        <h5 class="card-title">List Send</h5>
        <div class="header-elements">
            <button type="button" @click="createModal" class="btn bg-indigo-400 btn-labeled btn-labeled-left rounded-round"><b><i class="icon-plus-circle2"></i></b> Add Data</button>
        </div>
	</div>

	<table class="table table-hover table-striped table-xs text-nowrap" id="datatable_basic">
		<thead>
			<tr>
				<th>#</th>
                <th class="text-center">Actions</th>
                <th>Title</th>
                <th>status</th>
                <th>Client phone</th>
                <th>Type</th>
                <th>Created At</th>
                <th>Updated At </th>
                <th>Created By</th>
                <th>Updated By </th>
			</tr>
		</thead>
		<tbody>
			<tr v-if="mainData" v-for="item, index in mainData" :key="index">
				<td v-text="index+1"></td>
                <td style="width: 16px;">
                    <div class="btn-group">
                        <button type="button" class="btn btn-outline bg-info-600 text-info-600 btn-icon btn-sm rounded-round ml-2"
                            data-popup="tooltip" title="" data-placement="left" data-original-title="Edit" @click="editModal(item)">
                            <i class="fas fa-pencil-alt"></i></button>
                        <button type="button" class="btn btn-outline bg-danger-600 text-danger-600 btn-icon btn-sm rounded-round ml-2"
                            data-popup="tooltip" title="" data-placement="left" data-original-title="Delete" @click="deleteData(item.id)">
                            <i class="far fa-trash-alt"></i></button>
                        <button type="button" class="btn btn-outline bg-success-600 text-success-600 btn-icon btn-sm rounded-round ml-2"
                            data-popup="tooltip" title="" data-placement="left" data-original-title="Delete" @click="checkAccountNumber(item.id,item.client_id,item.broadcast_type_id)">
                            <i class="far icon-truck"></i></button>
                    </div>
                </td>
                <td v-text="item.title"></td>
                <td v-if="item.status===0">Blm terkirim</td>
                <td v-else>Terkirim</td>

                <td v-if="item.broadcast_type_id===1" >-</td>
                <td v-else v-text="item.client_phone"></td>

              
                <td v-if="item.broadcast_type_id===1">Send to All</td>
                <td v-else v-text="'send to '+item.client_name"></td>
                <td v-text="item.created_at"></td>
                <td v-text="item.updated_at"></td>
                <td v-text="item.created_by"></td>
                <td v-text="item.updated_by"></td>
			</tr>
		</tbody>
	</table>
</div>
<!-- /basic datatable -->

<!-- Basic modal -->
<div id="modal_default" class="modal fade" tabindex="-1">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header" :class="editMode ? 'bg-info-600' : 'bg-indigo-400'">
                <h4 class="modal-title">@{{ (editMode ? 'Edit Data' : 'New Data') }}</h4>
				<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>

			<form @submit.prevent="editMode ? updateData() : storeData()" @keydown="form.onKeydown($event)">
				<div class="modal-body">
                    <div class="form-group">
                        <label for="broadcast_type">Payment Method</label>
                        <select id="broadcast_type" class="form-control select-search" data-placeholder="Pilih group..." onchange="app.select2Changed('broadcast_type', this.value)">
                            <option value=""></option>
                            <option v-for="item in dataType" :key="item.id" :value="item.id">@{{ item.type }}</option>
                        </select>
                        <span class="manual-error" v-if="form.errors.has('broadcast_type')">Pilih Merek type</span>
                    </div>
                    
                    <div class="form-group">
                        <label for="client_id">Client</label>
                        <select id="client_id" class="form-control select-search" data-placeholder="Choice client name..." onchange="app.select2Changed('client_id', this.value)" :disabled="form.broadcast_type != 2">
                            <option value=""></option>
                            <option v-for="item in dataClient" :key="item.id" :value="item.id">@{{ item.client_phone+" | "+item.client_name }}</option>
                        </select>
                        <span class="manual-error" v-if="form.errors.has('client_id')">Choice client name</span>
                    </div>
                    <div class="form-group">
                        <label for="message_id">Message</label>
                        <select id="message_id" class="form-control select-search" data-placeholder="Choice client name..." onchange="app.select2Changed('message_id', this.value)">
                            <option value=""></option>
                            <option v-for="item in dataMessage" :key="item.id" :value="item.id">@{{ item.title }}</option>
                        </select>
                        <span class="manual-error" v-if="form.errors.has('message_id')">Choice client name</span>
                    </div>
				</div>

				<div class="modal-footer">
                    <button type="button" class="btn btn-light" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-ladda btn-ladda-submit" :class="editMode ? 'bg-info-600' : 'bg-indigo-400'">
						@{{ editMode ? 'Update' : 'Save' }}
					</button>
				</div>
			</form>
		</div>
	</div>
</div>
<!-- /basic modal -->
@endsection

@push('js')
<script>
    var app = new Vue({
        el: '#app',
        data: {
        	mainData: [],
            editMode : false,
            form : new Form({
                id: '',
                broadcast_type:0,
                client_id: "",
                message_id: 0,
            }),
            dataType: @json($dataType),
            dataClient: @json($dataClient),
            dataMessage: @json($dataMessage),
        },
        mounted() {
            $('.select-search').select2();
	        $('#datatable_basic').DataTable();
	        this.refreshDatatable();
        },
        
        methods: {
            select2Changed(field, value){
                if (field == 'broadcast_type') return this.form.broadcast_type = value
                if (field == 'client_id') return this.form.client_id = value
                if (field == 'message_id') return this.form.message_id = value
                
            },
            createModal(){
                this.editMode = false;
                this.form.reset();
                this.form.clear();
                console.log();
                $('#broadcast_type').val('').trigger('change')
                $('#client_id').val('').trigger('change')
                $('#message_id').val('').trigger('change')
                $('#modal_default').modal('show');
            },
            editModal(data){
                this.editMode = true;
                this.form.fill(data);
                this.form.clear();
                $('#broadcast_type').val(data.broadcast_type).trigger('change')
                $('#message_id').val(data.message_id).trigger('change')
                $('#client_id').val(data.client_id).trigger('change')
                if(data.client_id==0){
                    $('#client_id').val('All').trigger('change')
                }else{
                    $('#client_id').val(data.client_phone).trigger('change')
                }
                // console.log(data.client_phone);
                $('#modal_default').modal('show');
            },
            storeData(){
                l = laddaButton('.btn-ladda-submit')
                l.start();

                this.form.post("{{ route('send.store') }}")
                    .then(response => {
                        basicFormSuccess('Data telah disimpan')
                        this.refreshDatatable()
                        setTimeout(() => { $('#modal_default').modal('hide') }, 1500);
                    })
                    .catch(e => {
                        basicFormError(e)
                    })
                    .finally(ok => {
                        setTimeout(() => { l.setProgress(0.5) }, 500);
                        setTimeout(() => { l.stop(); l.remove() }, 1300);
                    })
            },
            updateData(){
                l = laddaButton('.btn-ladda-submit')
                l.start();

                url = "{{ route('send.update', ':id') }}".replace(':id', this.form.id)
                this.form.put(url)
                    .then(response => {
                        basicFormSuccess('Data telah diupdate')
                        this.refreshDatatable()
                        setTimeout(() => { $('#modal_default').modal('hide') }, 1500);
                    })
                    .catch(e => {
                        basicFormError(e)
                    })
                    .finally(ok => {
                        setTimeout(() => { l.setProgress(0.5) }, 500);
                        setTimeout(() => { l.stop(); l.remove() }, 1300);
                    })
            },
            deleteData(id){
                DeleteConfirmation.fire().then((result) => {
                    if (result.value) {
                        url = "{{ route('send.destroy', ':id') }}".replace(':id', id)
                        axios.delete(url)
                            .then(response => {
                                basicFormSuccess('Data berhasil dihapus')
                                this.refreshDatatable()
                            })
                            .catch(e => {
                                basicFormError(e)
                            })
                    }
                })
            },
            
            checkAccountNumber(id,client_id,broadcast_type_id){
                // axios.post("{{ route('send.send') }}",{id :id,client_id:client_id,broadcast_type_id:broadcast_type_id})
                // .then(function (response) {
                //    // handle success
                //    console.log(response);
                //  })
                SendConfirmation.fire().then((result) => {
                    if (result.value) {
                axios.post("{{ route('send.send') }}",{id :id,client_id:client_id,broadcast_type_id:broadcast_type_id})
                    .then(response => {
                        // console.log(response.data.status);

                        basicFormSuccess(response.data.statusDesc)
                        this.refreshDatatable()
                        setTimeout(() => { $('#modal_default').modal('hide') }, 1500);
                    })
                    .catch(e => {
                        basicFormError(e)
                    })
                    }
                })
            },
            refreshDatatable(){
            	axios.get("{{ route('send.all') }}")
                    .then(response => {
                        $('#datatable_basic').DataTable().destroy();
                        this.mainData = response.data
                        this.$nextTick(function() {
                            $('#datatable_basic').DataTable({
                                dom: '<"datatable-header "fBl><"datatable-scroll-wrap"t><"datatable-footer"ip>',
                                drawCallback: function(){
                                    $('[data-popup="tooltip"]').tooltip({trigger : 'hover'});
                                }
                            });
                            redrawTable();
                        })
                    })
                    .catch(e => {
                        basicFormError(e)
                    })
            }
        },
    })
</script>
@endpush